accounts:
  - name: alice
    coins: ["1000token", "100000000stake"]
  - name: bob
    coins: ["500token"]
  - name: son
    coins: ["1000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["5token"]
host:
  api: "0.0.0.0:1317"
  rpc: "0.0.0.0:26657"

